FROM postgres:14

WORKDIR /var/app/test-fastapi

# CMD [psql -h 127.0.0.1 -p 5432 -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f ./database/postgresql/create.sql]

# psql -h localhost -p 5432 -U postgres -d postgres -f ./database/postgresql/create_table.sql